export const councils = [
    "Andhra Pradesh Medical Council",
    "Arunachal Pradesh Medical Council",
    "Assam Medical Council",
    "Bihar Medical Council",
    "Chattisgarh Medical Council",
    "Delhi Medical Council",
    "Goa Medical Council",
    "Gujarat Medical Council",
    "Haryana Medical Council",
    "Himanchal Pradesh Medical Council",
    "Jammu & Kashmir Medical Council",
    "Jharkhand Medical Council",
    "Karnataka Medical Council",
    "Madhya Pradesh Medical Council",
    "Maharashtra Medical Council",
    "Manipur Medical Council",
    "Mizoram Medical Council",
    "Nagaland Medical Council",
    "Orissa Council of Medical Registration",
    "Punjab Medical Council",
    "Rajasthan Medical Council",
    "Sikkim Medical Council",
    "Tamil Nadu Medical Council",
    "Telangana State Medical Council",
    "Travancore Cochin Medical Council",
    "Tripura State Medical Council",
    "Uttarakhand Medical Council",
    "Uttar Pradesh Medical Council",
    "West Bengal Medical Council",
  ];
  
  export const degrees = [
    "MBBS",
    "BDS",
    "BHMS",
    "BAMS",
    "BUMS",
    "BSMS",
    "BNYS",
    "BPT",
    "B.Sc Nursing",
    "MD",
    "MS",
    "MDS",
    "MPT",
    "PhD in Medical Sciences",
    "M.Phil",
    "DNB",
    "DM",
    "MCh",
    "Diploma in Medical Lab Technology",
    "Diploma in Radiology",
    "Diploma in Anaesthesia",
    "Diploma in Clinical Pathology",
    "Diploma in Dermatology",
    "Diploma in Child Health",
    "PG Diploma in Public Health",
    "PG Diploma in Obstetrics & Gynaecology",
    "PG Diploma in Pediatrics",
    "PG Diploma in Orthopaedics",
  ];
  
  export   const stateList = [
    {
      label: "Andaman and Nicobar Islands",
      value: "Andaman and Nicobar Islands",
    },
    { label: "Andhra Pradesh", value: "Andhra Pradesh" },
    { label: "Arunachal Pradesh", value: "Arunachal Pradesh" },
    { label: "Assam", value: "Assam" },
    { label: "Bihar", value: "Bihar" },
    { label: "Chandigarh", value: "Chandigarh" },
    { label: "Chhattisgarh", value: "Chhattisgarh" },
    { label: "Dadra and Nagar Haveli", value: "Dadra and Nagar Haveli" },
    { label: "Daman and Diu", value: "Daman and Diu" },
    { label: "Delhi", value: "Delhi" },
    { label: "Goa", value: "Goa" },
    { label: "Gujarat", value: "Gujarat" },
    { label: "Haryana", value: "Haryana" },
    { label: "Himachal Pradesh", value: "Himachal Pradesh" },
    { label: "Jammu and Kashmir", value: "Jammu and Kashmir" },
    { label: "Jharkhand", value: "Jharkhand" },
    { label: "Karnataka", value: "Karnataka" },
    { label: "Kerala", value: "Kerala" },
    { label: "Lakshadweep", value: "Lakshadweep" },
    { label: "Madhya Pradesh", value: "Madhya Pradesh" },
    { label: "Maharashtra", value: "Maharashtra" },
    { label: "Manipur", value: "Manipur" },
    { label: "Meghalaya", value: "Meghalaya" },
    { label: "Mizoram", value: "Mizoram" },
    { label: "Nagaland", value: "Nagaland" },
    { label: "Odisha", value: "Odisha" },
    { label: "Puducherry", value: "Puducherry" },
    { label: "Punjab", value: "Punjab" },
    { label: "Rajasthan", value: "Rajasthan" },
    { label: "Sikkim", value: "Sikkim" },
    { label: "Tamil Nadu", value: "Tamil Nadu" },
    { label: "Telangana", value: "Telangana" },
    { label: "Tripura", value: "Tripura" },
    { label: "Uttar Pradesh", value: "Uttar Pradesh" },
    { label: "Uttarakhand", value: "Uttarakhand" },
    { label: "West Bengal", value: "West Bengal" },
  ];


  export const GOOGLE_AUTO_COMPLETE_API_KEY = "AIzaSyDiKV3OLHnGFYI4qhcIKjk7tzG-RXeUI5s"

  export const dosageForms = [
    "Tablets", "Capsules", "Chewable Tablets", "Syrups", "Drops", "Ointments", "Gels", "Vials", "Inhalers", "Sachet/Granules", "Sprays", "Powders", "Ointments",
  ]

  export const testTypeOptions = [
    { label: "Blood", value: "blood" },
    { label: "Diagnostic", value: "diagnostic" },
    { label: "Radiology", value: "ctmri" },
    { label: "Dental care", value: "dental_care" },
    { label: "Eye care", value: "eye_care" },
    { label: "Spa", value: "spa" },
    { label: "Zumb", value: "zumb" },
    { label: "Yoga", value: "yoga" },
    { label: "Eldc", value: "eldc" },
    { label: "Ayurveda", value: "ayurveda" },
    { label: "Dc", value: "dc" },
    { label: "Wc", value: "wc" },
    { label: "Plte", value: "plte" },
    { label: "Box", value: "box" },
    { label: "Gz", value: "gz" },
    { label: "Ambu", value: "ambu" },
    { label: "Thrp", value: "thrp" },
    { label: "Phsy", value: "phsy" },
    { label: "Gym", value: "gym" },
    { label: "Vaccination", value: "vaccination" },
  ];