// Country codes data with country names and their respective dialing codes
export interface CountryCode {
  code: string; // Numeric code without '+'
  country: string; // Country name
  flag?: string; // Optional flag emoji
}

export const countryCodes: CountryCode[] = [
  { code: "91", country: "India", flag: "🇮🇳" },
  { code: "1", country: "United States", flag: "🇺🇸" },
  { code: "44", country: "United Kingdom", flag: "🇬🇧" },
  { code: "61", country: "Australia", flag: "🇦🇺" },
  { code: "86", country: "China", flag: "🇨🇳" },
  { code: "49", country: "Germany", flag: "🇩🇪" },
  { code: "33", country: "France", flag: "🇫🇷" },
  { code: "81", country: "Japan", flag: "🇯🇵" },
  { code: "7", country: "Russia", flag: "🇷🇺" },
  { code: "55", country: "Brazil", flag: "🇧🇷" },
  { code: "39", country: "Italy", flag: "🇮🇹" },
  { code: "34", country: "Spain", flag: "🇪🇸" },
  { code: "82", country: "South Korea", flag: "🇰🇷" },
  { code: "1", country: "Canada", flag: "🇨🇦" },
  { code: "52", country: "Mexico", flag: "🇲🇽" },
  { code: "31", country: "Netherlands", flag: "🇳🇱" },
  { code: "65", country: "Singapore", flag: "🇸🇬" },
  { code: "971", country: "United Arab Emirates", flag: "🇦🇪" },
  { code: "966", country: "Saudi Arabia", flag: "🇸🇦" },
  { code: "27", country: "South Africa", flag: "🇿🇦" },
  { code: "41", country: "Switzerland", flag: "🇨🇭" },
  { code: "46", country: "Sweden", flag: "🇸🇪" },
  { code: "47", country: "Norway", flag: "🇳🇴" },
  { code: "45", country: "Denmark", flag: "🇩🇰" },
  { code: "358", country: "Finland", flag: "🇫🇮" },
  { code: "48", country: "Poland", flag: "🇵🇱" },
  { code: "43", country: "Austria", flag: "🇦🇹" },
  { code: "32", country: "Belgium", flag: "🇧🇪" },
  { code: "351", country: "Portugal", flag: "🇵🇹" },
  { code: "30", country: "Greece", flag: "🇬🇷" },
  { code: "64", country: "New Zealand", flag: "🇳🇿" },
  { code: "353", country: "Ireland", flag: "🇮🇪" },
  { code: "92", country: "Pakistan", flag: "🇵🇰" },
  { code: "880", country: "Bangladesh", flag: "🇧🇩" },
  { code: "94", country: "Sri Lanka", flag: "🇱🇰" },
  { code: "977", country: "Nepal", flag: "🇳🇵" },
  { code: "975", country: "Bhutan", flag: "🇧🇹" },
  { code: "960", country: "Maldives", flag: "🇲🇻" },
  { code: "95", country: "Myanmar", flag: "🇲🇲" },
  { code: "62", country: "Indonesia", flag: "🇮🇩" },
  { code: "60", country: "Malaysia", flag: "🇲🇾" },
  { code: "66", country: "Thailand", flag: "🇹🇭" },
  { code: "84", country: "Vietnam", flag: "🇻🇳" },
  { code: "63", country: "Philippines", flag: "🇵🇭" },
  { code: "855", country: "Cambodia", flag: "🇰🇭" },
  { code: "856", country: "Laos", flag: "🇱🇦" },
  { code: "853", country: "Macau", flag: "🇲🇴" },
  { code: "852", country: "Hong Kong", flag: "🇭🇰" },
  { code: "886", country: "Taiwan", flag: "🇹🇼" },
];